### ISSUE TITLE
OpenSSL method deprecation warning

### ISSUE THREAD

**Issue by courtland** [technoweenie/sentry#1]
.../lib/sentry/symmetric_sentry.rb:25: warning: argumtents for OpenSSL::Cipher::Cipher#encrypt and OpenSSL::Cipher::Cipher#decrypt were deprecated; use OpenSSL::Cipher::Cipher#pkcs5_keyivgen to derive key and IV

**Comment by lylo** [comment]
Did you get anywhere with this?

**Comment by courtland** [comment]
No

**Comment by lylo** [comment]
I'd recommend moving from Sentry to http://github.com/shuber/attr_encrypted/ -- it's awesome.

**Comment by PatrickTulskie** [comment]
I can't really switch to another gem or encryption scheme right now so I've been trying to figure this out myself.  It's happening in the ossl_cipher_init method inside of ossl_cypher.c of the Ruby core.  I can use the pkcs5_keyivgen call without a salt and get the encryption/decryption to work, but the gem's tests fail because it's essentially a different encryption scheme.  Any thoughts on how to coerce the OpenSSL::Cipher class into being backwards compatible without throwing warnings?

**Comment by courtland** [comment]
I ended up moving to Sentry a while back and figured out how to re-encrypt my existing records via a migration. So far its worked flawlessly.
